AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  RepoSummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs18.x
      Events:
        GetSummary:
          Type: Api
          Properties:
            Path: /repo-summary
            Method: get
      Environment:
        Variables:
          DYNAMO_ENDPOINT: http://host.docker.internal:8000
