Resources:
  RepoSummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      PackageType: Zip
      Runtime: go1.x
      Handler: bootstrap
      CodeUri: cmd/repo-summary/
      Events:
        GetSummary:
          Type: Api
          Properties:
            Path: /repo-summary
            Method: get
      Environment:
        Variables:
          DYNAMO_ENDPOINT: http://host.docker.internal:8000
