name: Deploy Lambda API

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Go binary on Amazon Linux 2 (Lambda Compatible)
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app amazonlinux:2 bash -c "\
            yum install -y golang gcc zip && \
            go version && \
            GOOS=linux GOARCH=amd64 go build -o main cmd/repo-summary/main.go && \
            zip function.zip main"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name "pytori-be" \
            --zip-file fileb://function.zip
