name: Deploy Lambda API

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build Go binary for Lambda
        run: |
          GOOS=linux GOARCH=amd64 go build -o bootstrap main.go
          zip function.zip bootstrap

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name "pytori-be" \
            --zip-file fileb://function.zip
